### ISSUE TITLE
unable to compile with 1.86.0

### ISSUE THREAD

**Issue by halkeye** [sugyan/tuisky#55]
I'll admit i have very limited experience with rust

```
cargo version
cargo 1.86.0 (adf9b6ad1 2025-02-28)
```

```
cargo install tuisky
   Compiling tuisky v0.2.0
error[E0432]: unresolved import `bsky_sdk::api::agent::Session`
  --> /home/halkeye/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tuisky-0.2.0/src/components/column.rs:11:5
   |
11 | use bsky_sdk::api::agent::Session;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `Session` in `agent`

error[E0432]: unresolved import `bsky_sdk::api::agent::Session`
 --> /home/halkeye/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tuisky-0.2.0/src/components/views/post.rs:5:5
  |
5 | use bsky_sdk::api::agent::Session;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `Session` in `agent`

error[E0308]: mismatched types
   --> /home/halkeye/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tuisky-0.2.0/src/components/modals/embed_record.rs:154:21
    |
154 |                     rkey,
    |                     ^^^^ expected `RecordKey`, found `String`

Some errors have detailed explanations: E0308, E0432.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `tuisky` (lib) due to 3 previous errors
warning: build failed, waiting for other jobs to finish...
    Building [=======================> ] 300/302: bsky-sdk
error: failed to compile `tuisky v0.2.0`, intermediate artifacts can be found at `/tmp/cargo-installsbcQr1`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

**Comment by halkeye** [comment]
checkout and cargo build does work

**Comment by sugyan** [comment]
It seems that the build had failed due to incompatible changes in the dependent libraries. This has been fixed and `v0.2.1` is now available.
https://crates.io/crates/tuisky/0.2.1
